# Generated by Django 4.2.5 on 2023-10-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='animal_images/')),
                ('nombre', models.CharField(max_length=40)),
                ('sexo', models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], max_length=20)),
                ('edad', models.IntegerField()),
                ('tamaño', models.CharField(choices=[('Chico', 'Chico'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=40)),
                ('raza', models.CharField(max_length=40)),
                ('caracteristicas', models.TextField(blank=True)),
                ('cuidados_especiales', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cuidados Especiales')),
                ('especie', models.CharField(blank=True, choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(blank=True, choices=[('Veterinario General', 'Veterinario General'), ('Veterinario de Animales Exóticos', 'Veterinario de Animales Exóticos'), ('Emergencias y Cuidados Críticos', 'Emergencias y Cuidados Críticos'), ('Cirujano Veterinario', 'Cirujano Veterinario'), ('Dentista Veterinario', 'Dentista Veterinario'), ('Dermatólogo Veterinario', 'Dermatólogo Veterinario'), ('Cardiólogo Veterinario', 'Cardiólogo Veterinario'), ('Oftalmólogo Veterinario', 'Oftalmólogo Veterinario'), ('Oncólogo Veterinario', 'Oncólogo Veterinario'), ('Neurólogo Veterinario', 'Neurólogo Veterinario'), ('Radiología Veterinaria', 'Radiología Veterinaria'), ('Rehabilitación Veterinaria', 'Rehabilitación Veterinaria')], max_length=40)),
            ],
        ),
    ]
